# Generated by Django 5.1.7 on 2025-05-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.SmallIntegerField(choices=[(1, 'Clarice Lispector'), (2, 'Fyodor Dostoevsky'), (3, 'Gabriel García Márquez'), (4, 'Jorge Luis Borges'), (5, 'Machado de Assis'), (6, 'Ariano Suassuna'), (7, 'J.R.R. Tolkien'), (8, 'George R.R. Martin')])),
                ('ano', models.IntegerField()),
                ('foto', models.URLField(blank=True, null=True)),
                ('numero_de_paginas', models.IntegerField(blank=True, null=True)),
                ('disponivel', models.ImageField(blank=True, null=True, upload_to='livro/fotos')),
            ],
        ),
    ]
