# Generated by Django 5.1.7 on 2025-06-01 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='livro/fotos'),
        ),
    ]
